#!/usr/bin/env sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

readonly message_file="proto/gen/go/muninn/v1/service.pb.go"
readonly service_file="proto/gen/go/muninn/v1/service_grpc.pb.go"

actual_files=$(find proto/gen/go/muninn/v1 -maxdepth 1 -type f -print | LC_ALL=C sort)
expected_files=$(printf '%s\n%s' "$message_file" "$service_file")
if [ "$actual_files" != "$expected_files" ]; then
  echo "unexpected generated protobuf file set:" >&2
  printf '%s\n' "$actual_files" >&2
  exit 1
fi

require_fixed() {
  needle=$1
  file=$2
  if ! grep -Fq "$needle" "$file"; then
    echo "generated protobuf validation failed: ${file} lacks ${needle}" >&2
    exit 1
  fi
}

require_fixed '// Code generated by protoc-gen-go. DO NOT EDIT.' "$message_file"
require_fixed '// Code generated by protoc-gen-go-grpc. DO NOT EDIT.' "$service_file"
require_fixed 'protoc-gen-go v1.36.11' "$message_file"
require_fixed 'protoc-gen-go-grpc v1.6.2' "$service_file"
require_fixed 'ProtoReflect() protoreflect.Message' "$message_file"

for method in Hello Write BatchWrite Read Forget Stat Link Activate Subscribe; do
  if ! grep -Eq \
    "^[[:space:]]*MuninnDB_${method}_FullMethodName[[:space:]]*=[[:space:]]*\"/muninn\\.v1\\.MuninnDB/${method}\"$" \
    "$service_file"; then
    echo "generated protobuf validation failed: missing canonical ${method} RPC path" >&2
    exit 1
  fi
done
